# Generated by Django 5.2.17 on 2026-09-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='completion_photo',
            field=models.ImageField(blank=True, null=True, upload_to='task_photos/completion/'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='issue_photo',
            field=models.ImageField(default='', upload_to='task_photos/issue/'),
            preserve_default=False,
        ),
    ]
