# Generated by Django 5.2.17 on 2026-09-05 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancetask_completion_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('URGENT', 'Urgent'), ('NORMAL', 'Normal'), ('LOW', 'Low')], max_length=20)),
                ('interval_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('last_generated_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
